version: "2.2"
services:
  clickhouse:
    image: yandex/clickhouse-server:21.3.20
    container_name: clickhouse
    ulimits:
      nofile: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./config/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8123:8123
      - 9000:9000
    networks:
      - local-net

networks:
  local-net:
    external: true
